insert into Entrada (instruccion) values ('B BodegaRioja');
insert into Entrada (instruccion) values ('C');
insert into Entrada (instruccion) values ('V BLANCA 3000');
insert into Entrada (instruccion) values ('V NEGRA 2000');
insert into Entrada (instruccion) values ('B BodegaPriorat');
insert into Entrada (instruccion) values ('C');
insert into Entrada (instruccion) values ('V NEGRA 4000');
insert into Entrada (instruccion) values ('V NEGRA 1000');
insert into Entrada (instruccion) values ('V BLANCA 2000');
insert into Entrada (instruccion) values ('#');
insert into Entrada (instruccion) values ('B BodegaRibera');
insert into Entrada (instruccion) values ('B BodegaPenedes');
insert into Entrada (instruccion) values ('C');
insert into Entrada (instruccion) values ('B BodegaRueda');
insert into Entrada (instruccion) values ('V NEGRA 4000');
insert into Entrada (instruccion) values ('V BLANCA 2000');
insert into Entrada (instruccion) values ('V NEGRA 4000');
insert into Entrada (instruccion) values ('#');
insert into Entrada (instruccion) values ('V NEGRA 2000');
insert into Entrada (instruccion) values ('V BLANCA 4000');
insert into Entrada (instruccion) values ('C');
insert into Entrada (instruccion) values ('C');
insert into Entrada (instruccion) values ('V BLANCA 4000');
insert into Entrada (instruccion) values ('#');
